### PR TITLE
Testing refactor

### LINKED ISSUE #33: Add testing for frontend components

### LINKED ISSUE #35: Frontend tests need to be remade to fit the new structure of questions/components

### LINKED ISSUE #43: Update testing and README
Please improve your testing (and make sure you pass them), and instructions on how to run tests in your README!
Other teams will need to set up and test your system in peer review next week.

### PR DESCRIPTION
**Pull request by jgao222**
Hopefully fix testing on the front end.
- use `ts-jest`
- use a jest config
  - ignore `.css` in the React tests
- use a hack from https://github.com/jsdom/jsdom/issues/1724#issuecomment-1446858041 to be able to spyon/mock `fetch` calls (which is unsupported by `jsdom` environment)
- probably more stuff?

### CODE REVIEW

**Comment by winstonbullen** [comment]
Still getting errors on my end with the Jest parser. The CI also still seems to fail. We can discuss and try together during the team meeting today.

**Comment by jgao222** [comment]
After running this on Attu, I've identified two problems:
- for some reason on windows the resolution for the environment file isn't case sensitive, where on linux it is, so `FixJSDomEnvironment.ts` needs to be renamed to `FixJSDOMEnvironment.ts` which is how it is written in the jest config.
- the workaround to being able to mock the fetch command in JSDOM only works in Node >=18, which means our CI which is set up to run on Node 16 and Node 18 will always fail on Node 16.

Not sure how to proceed here, since fixing esp. the last bullet point will either require changing the tests to mock the fetch calls some other way, or removing Node 16 from tested versions (which will also mean our project isn't guaranteed to work on Attu anymore since attu is running Node 16).

**Comment by winstonbullen** [comment]
Do we *need* to support attu? I think that as long as it works on our machines for development and the hosting service we choose for deployment then it's fine. It would simplify the CI tests as well. I think @uwjaxu is going to take a look at this branch before we try anything else.

**Comment by jgao222** [comment]
Pushed the fix for the case-sensitivity issue that I forgot. We never discussed which versions of Node we were targeting, but we never mention Node 16 in any of the documentation, nor are any of us developing on it, so it is okay to drop it. We should maybe note that the project only works on Node 18 in the developer documentation (though it is mentioned already in the frontend and backend readmes).

**Comment by winstonbullen** [comment]
Looks good to me (have not run it yet on my machine)! I think we are ready to merge per approval of @uwjaxu sometime soon.

**Comment by jgao222** [comment]
Frontend fails to build with the changes I made. Need to add build to the CI pipeline to ensure it can successfully compile.

**Comment by winstonbullen** [comment]
The testing works on my machine, but the questions fail to appear upon clicking the first lesson on local host deployment. Does this work on your machine @jgao222 ?

**Pull request merged**
