### PR TITLE
Progress tracking

### LINKED ISSUE #58: Track User Progress
This involves using the `completed` field in the users API to append and retrieve completed lessons. This means front end should update styling to reflect these completions. This could probably just be a green indicator somewhere on the menu item. This also means the logic for tracking the completion of a lesson real-time should be completed. Further, the username in the bottom left of the homepage should be changed to the current user's username instead of "CoolCoder123". 

To track a completed lesson, append a string to the `completed` field mentioned above, which is an array. The format for these are `"{language}_{subject}_{lesson_number}"`, so the first lesson should be `"java_variables_1"`. The milestone quiz at the end of a unit should just be `"{language}_{subject}"`, so `"java_variables"` for the first unit.

Read the `completed` field upon user login to populate the menu completions. Using the first unit as an example, a completed unit should include the following:
- `"java_variables_1"` for lesson 1
- `"java_variables_2"` for lesson 2
- `"java_variables_3"` for lesson 3
- `"java_variables"` for the milestone quiz pass

Only track completion at this abstraction, so do not track completion of individual questions. Lessons are all-or-nothing, so if they do one problem then exit, no progress should be saved.

### PR DESCRIPTION
**Pull request by evanhkim**
Tracks when a user completes a lesson and sends post request on the question.ts file. 
On index uses get to create a set of completed lessons to check for completion. On completion logic for UI is only done for checkpoint 1 of unit 1.
Also added a prop to the question component to track if a lesson is already completed to avoid duplicates on the backend completions data. 
Still hardcodes the language and should be updated to dynamically change based on the language user is learning in the future.

### CODE REVIEW

**Comment by winstonbullen** [comment]
Looks like a good start. It appears the lesson is not marked as completed immediately after completing it, though. Only upon login does it change color. Is this reproducible on your end?

**Comment by evanhkim** [comment]
I only have the first checkpoint ui working for indicating completion, but the short delay is probably because I used the useffect hook which updates stuff right after render.

**Comment by winstonbullen** [comment]
Got it. I think fixing that is a priority before merging. I also think that we can change the styling of the completion as mentioned in the Slack thread.

**Comment by evanhkim** [comment]
fixed the lag in update / requiring a page reload to be seen. the styling I think can be done with some discussion as a group on how we want to finalize the home page.

**Comment by winstonbullen** [comment]
Looks good! Let's take the discussion to Slack.

**Review by winstonbullen — APPROVED** [review]
Looks good. Style change can happen at a later date.

**Pull request merged**
