### PR TITLE
Integrate Persistent MongoDB

### LINKED ISSUE #11: Create NoSQL Content Database

### LINKED ISSUE #12: Create NoSQL User Database

### LINKED ISSUE #13: Connect Databases to Backend Language

### PR DESCRIPTION
**Pull request by winstonbullen**
This PR creates a MongoDB Atlas instance to serve content and user data. This allows for persistent data. The tests were updated accordingly. This also adds a GitHub CI secret key for the database password. This allows the CI to run the tests.

### CODE REVIEW

**Comment by winstonbullen** [comment]
DO NOT MERGE RIGHT NOW! There will be a comment left here when merging can be considered.

**Comment by jgao222** [comment]
I believe this is working now @winstonbullen. I had to remove two of the tests from the User Info DB tests because they deal with appending to the completion list, and since the database is real and persistent now each time the tests are run they would keep appending to that entry, meaning it's not great to check equality.

**Comment by winstonbullen** [comment]
Sounds good. I was thinking we could implement a couple functions to remove entries, though. They wouldn't be part of the API, but rather an internal tool. The remove functions could be called after the test assertions, for example. Thoughts? @jgao222

**Comment by jgao222** [comment]
That could be good. I'm going to work on some other stuff tonight so I'll take a look at that tomorrow. If you want to explore implementing that as well, feel free.

**Comment by winstonbullen** [comment]
We can leave that for after Beta release. Do you think we are in a good position to merge? I can tomorrow morning after I do another style pass.

**Comment by winstonbullen** [comment]
Currently having trouble with signup and login. Getting a 401 access denied error. I am thinking there is a small error in the endpoint logic. The tests work fine, which is odd. It also seems like the users db is not being updated in the Atlas portal?

**Pull request merged**
