### PR TITLE
Final Release Docs

### LINKED ISSUE #70: incorrect when missing space for typing questions
Screenshot 2023-05-23 at 3 02 22 PM

### LINKED ISSUE #81: Address Short Response Whitespace Validation
Currently short response questions only direct string match. This means that whitespace is expected to be a certain length when it can actually be flexible. For now, this should likely be under a `Help` section covering user documentation. This should address #70.

### PR DESCRIPTION
**Pull request by winstonbullen**
This revamps the user documentation to be mostly contained within its own page. This page is `help.html` and is served from the backend. The `/help` GET endpoint serves it. The images on the `Help` page should be updated prior to final release. The `Help` page section on short response formatting is also linked on every short response question. This closes #81 and closes #70.

### CODE REVIEW

**Review by jgao222 — COMMENTED** [review]
Looks good. All the changes are positive and will help the user experience.

I will note that the `homepage.png` is probably going to need to change, and that the `milestone.png` is off-center, and has a little bit of the drop shadow from the lesson above it (so looks a bit odd on the help page).
image

**Comment by winstonbullen** [comment]
Good job pointing out the drop shadow from the lessons in the milestones image. I figured keeping it off center was fine because it preserves the relative positioning of the milestone from the actual homepage. Since you pointed this out, I will fix it because it will clearly confuse others.

**Comment by jgao222** [comment]
> I figured keeping it off center was fine because it preserves the relative positioning of the milestone from the actual homepage.

I don't think every milestone icon will be off-center in the same way as the first subject either, so I think it will be better to just show the icon itself.

**Comment by winstonbullen** [comment]
Good point. Pushed a fix and let me know what you think.

**Review by jgao222 — APPROVED** [review]
The drop shadow is still just slightly visible. Is it not possible to take screenshot of just the milestone icon? Either way it looks good enough for now. I'll approve this, merge when you feel it is ready.

**Pull request merged**
